configDirectory: "./hms.conf"
# seconds
reporterLife:  60
# seconds
reporterInterval: 1
config:
- MAX_CONCURRENT_PROCESSORS: 10
  PROCESSOR_BUCKET_SIZE: 20
  # MAX_ALERT_CONCURRENT_PROCESSORS: 100
  # ALERT_BUCKET_SIZE: 100
# - MAX_CONCURRENT_PROCESSORS: 10
#   PROCESSOR_BUCKET_SIZE: 30
#   # MAX_ALERT_CONCURRENT_PROCESSORS: 100
#   # ALERT_BUCKET_SIZE: 100
# - MAX_CONCURRENT_PROCESSORS: 10
#   PROCESSOR_BUCKET_SIZE: 40
#   # MAX_ALERT_CONCURRENT_PROCESSORS: 100
#   # ALERT_BUCKET_SIZE: 100
# - MAX_CONCURRENT_PROCESSORS: 10
#   PROCESSOR_BUCKET_SIZE: 45
#   # MAX_ALERT_CONCURRENT_PROCESSORS: 100
#   # ALERT_BUCKET_SIZE: 100
